// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZetaTradingTechTask;

#nullable disable

namespace ZetaTradingTechTask.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231004130005_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ZetaTradingTechTask.Models.JournalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BodyParameters")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QueryParameters")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("JournalRecords");
                });

            modelBuilder.Entity("ZetaTradingTechTask.Models.Node", b =>
                {
                    b.Property<int>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("NodeId1")
                        .HasColumnType("int");

                    b.Property<int?>("ParentNodeId")
                        .HasColumnType("int");

                    b.HasKey("NodeId");

                    b.HasIndex("NodeId1");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("ZetaTradingTechTask.Models.Node", b =>
                {
                    b.HasOne("ZetaTradingTechTask.Models.Node", null)
                        .WithMany("ChildNodes")
                        .HasForeignKey("NodeId1");
                });

            modelBuilder.Entity("ZetaTradingTechTask.Models.Node", b =>
                {
                    b.Navigation("ChildNodes");
                });
#pragma warning restore 612, 618
        }
    }
}
